binop_separator = "Front"
comment_width = 100
enum_discrim_align_threshold = 30
error_on_line_overflow = true
fn_single_line = true
format_strings = true
imports_granularity = "Crate"
reorder_imports = true
max_width = 100
unstable_features = true
wrap_comments = true
